# Generated by Django 2.1.5 on 2022-03-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=20, unique=True)),
                ('content', models.TextField(default='')),
                ('rate', models.FloatField(default=0)),
                ('user_id', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('r_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('r_name', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=100)),
                ('r_phone_num', models.CharField(max_length=10)),
                ('r_email', models.CharField(max_length=30)),
                ('website_url', models.URLField()),
                ('menu', models.ImageField(upload_to='')),
                ('photo', models.ImageField(upload_to='')),
                ('overall_rate', models.FloatField()),
                ('category', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='finder.Restaurant'),
        ),
    ]
