# Generated by Django 4.0.3 on 2022-03-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_category_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='r_id',
        ),
    ]
