# Generated by Django 2.1.5 on 2022-03-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20220308_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
