# Generated by Django 4.0.3 on 2022-03-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_remove_comment_c_id_remove_restaurant_r_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
