# Generated by Django 4.0.3 on 2022-03-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
